pom.xml, src/main/java/me/moodcat/api/RootApi.java, src/main/java/me/moodcat/models/BasicResponse.java
In order to use Lombok for #21 , you must run the jar located at .m2\repository\org\projectlombok\lombok\1.16.4\lombok-1.16.4.jar
- Updated BasicResponse to show the result of the @Data annotation.
- Updated RootApi to show usage of getters and setters
=> Added Lombok dependency to project.

pom.xml
Extracted some leftover dependency version to properties in pom.xml
=> Extracted dependency versions

README.md
Fixed the links to -Core instead of main repository.
=> Fixed links in readme.

.gitmodules, pom.xml, src/main/java/me/moodcat/core/App.java
- Add submodule for library
- Updated pom to include Recommendation-library
- Added sample code to App.java to show it compiles
=> Added recommendation-library to project for #16.

.gitignore, pom.xml, src/main/java/me/moodcat/api/ArtistAPI.java, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/MockData.java, src/main/java/me/moodcat/database/controllers/AbstractDAO.java, src/main/java/me/moodcat/database/controllers/ArtistDAO.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/database/entities/Artist.java, src/main/java/me/moodcat/database/entities/Song.java, src/main/resources/META-INF/persistence.xml, src/main/resources/logback.xml
Please run `mvn package` first
=> Setup for Hibernate, example entities, DAO's and API's

src/main/java/me/moodcat/soundcloud/SoundCloudAPIConnector.java, src/main/java/me/moodcat/soundcloud/SoundCloudExtract.java, src/main/java/me/moodcat/soundcloud/SoundCloudSearch.java, src/main/java/me/moodcat/soundcloud/SoundCloudTrack.java, src/main/java/me/moodcat/utils/network/UrlStreamFactory.java, src/test/java/me/moodcat/soundcloud/SoundCloudAPIConnectorTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudExtractTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudSearchTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudTrackTest.java
- Create new (mockable) class UrlStreamFactory to handle URL calls
- Created new class SoundCloudAPIConnector which uses the UrlStreamFactory
- Improved tests in order to be able to test own implementation without depending on the network
=> Improved SoundCloudAPI tests for #34.

src/main/java/me/moodcat/api/ProcessAPI.java, src/main/java/me/moodcat/mood/classifier/MoodClassifier.java, src/test/java/me/moodcat/mood/classifier/MoodClassifierTest.java
Merge into #47
In order to get started with #51
=> MoodCat classifier test #47

.gitignore, pom.xml, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/DbModule.java, src/main/resources/META-INF/persistence.xml, src/main/resources/persistence.properties, src/test/java/me/moodcat/database/DatabaseTestModule.java, src/test/resources/persistence.properties
Using Postgres on the src/main package (production/development)
Using H2 on the src/test package (development/test)
=> Postgres setting for Hibernate/JPA #45

src/main/java/me/moodcat/api/ChatAPI.java, src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/MockData.java, src/main/java/me/moodcat/database/controllers/AbstractDAO.java, src/main/java/me/moodcat/database/controllers/ArtistDAO.java, src/main/java/me/moodcat/database/controllers/ChatDAO.java, src/main/java/me/moodcat/database/controllers/RoomDAO.java, src/main/java/me/moodcat/database/entities/ChatMessage.java, src/main/java/me/moodcat/database/entities/Room.java, src/main/java/me/moodcat/database/entities/Song.java, src/main/resources/configuration/checkstyle.xml
Created ChatAPI for #18 .
Created Room and ChatMessage entities along with their respective DAO's.
I was unable to figure out how a ChatMessage could only store a roomId
instead of the full room, so that is room (no pun intended) for improvement.
=> Initial version of ChatAPI #18

pom.xml, src/main/java/me/moodcat/api/ProcessAPI.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/mood/Mood.java, src/main/java/me/moodcat/mood/classifier/MoodClassifier.java, src/test/java/me/moodcat/mood/classifier/MoodClassifierTest.java
=> Mood classifier

src/main/java/me/moodcat/api/ArtistAPI.java, src/main/java/me/moodcat/api/ChatAPI.java, src/main/java/me/moodcat/api/ProcessAPI.java, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/api/package-info.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/core/package-info.java, src/main/java/me/moodcat/database/DbModule.java, src/main/java/me/moodcat/database/controllers/ChatDAO.java, src/main/java/me/moodcat/database/controllers/package-info.java, src/main/java/me/moodcat/database/embeddables/package-info.java, src/main/java/me/moodcat/database/entities/Room.java, src/main/java/me/moodcat/database/entities/package-info.java, src/main/java/me/moodcat/database/package-info.java, src/main/java/me/moodcat/eemcsdata/parser/package-info.java, src/main/java/me/moodcat/mood/classifier/MoodClassifier.java, src/main/java/me/moodcat/mood/classifier/package-info.java, src/main/java/me/moodcat/mood/package-info.java, src/main/java/me/moodcat/soundcloud/SoundCloudAPIConnector.java, src/main/java/me/moodcat/soundcloud/package-info.java, src/main/resources/configuration/checkstyle.xml, src/test/java/me/moodcat/database/DatabaseTestModule.java
- Generated package-info.java for all packages
- Updated a lot of missing JavaDoc (still some to do)
- Persisted ChatMessages in the database whenever a message is posted
- Disabled 1 unnecessary warning (wasn't working properly)
- Removed duplicate Checkstyle modules
=> Fixed various checkstyle warnings.

src/main/java/me/moodcat/api/ChatAPI.java, src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/MockData.java, src/main/java/me/moodcat/database/entities/ChatMessage.java, src/main/java/me/moodcat/database/entities/Room.java, src/test/java/TestPackageAppRunner.java
We handled transactions per requests incorrectly
=> Fix for Guice JPA transactions

.gitignore, pom.xml, src/main/java/me/moodcat/api/ChatAPI.java, src/main/java/me/moodcat/api/ProcessAPI.java, src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/DbModule.java, src/main/java/me/moodcat/database/MockData.java, src/main/java/me/moodcat/database/entities/ChatMessage.java, src/main/java/me/moodcat/database/entities/Room.java, src/main/java/me/moodcat/mood/Mood.java, src/main/resources/persistence.properties, src/test/java/me/moodcat/database/DatabaseTestModule.java
Rebase of #58 
You must now run the App with environment variable database-password and the password as value.
Test environment still works as normal.
- Correctly indented pom.xml
- Added comment to clarify dehvub maven repository
- Removed duplicate pmd plugin in build phase
- Ignored some files.
- General Checkstyle fixes.
- Removed unused imports
- Added some JavaDoc comments to further clarify attribute usage
- Ignored some classes with checkstyle as they are intended that way
Rebased using 
```sh
git rebase -i -s recursive -X ours master
```
and configuration
```
pick 0aaf609 Reporting added to pom.xml
s 1c1c16a Updated pom.xml again and fixed 1 PMD issue.
s ce4e10c Ignored some files.
s 6e667e4 General Checkstyle fixes.
s 02ffb05 Changed properties again.
```
=> Reporting added to pom.xml

README.md, src/main/java/me/moodcat/database/DbModule.java
Added the installation instructions to the readme. This should explain new developers how to contribute to the project.
Please verify for both IDE's that this setup is correct and working.
=> Added installation instructions to readme

pom.xml, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/core/App.java, src/main/java/me/moodcat/database/DbModule.java, src/main/java/me/moodcat/database/controllers/AbstractDAO.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/database/embeddables/VAVector.java, src/main/java/me/moodcat/mood/Mood.java, src/main/java/me/moodcat/soundcloud/SoundCloudAPIConnector.java, src/main/java/me/moodcat/soundcloud/SoundCloudExtract.java, src/main/resources/configuration/pmd-rules.xml, src/test/java/me/moodcat/core/AppTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudIntegrationTest.java
Maven site now correctly runs again.
=> Maven site fixes #100 and fixes #93

src/main/java/me/moodcat/database/controllers/ArtistDAO.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/database/entities/Artist.java, src/main/java/me/moodcat/database/entities/Song.java, src/main/resources/configuration/checkstyle.xml
- Added Javadoc to Song
- Added Javadoc to Artist
- Added Javadoc to ArtistDAO
- Added Javadoc to SongDAO
- Removed non-functionaly Checkstyle warning.
0 CheckStyle warnings <3
=> Fixed all Checkstyle warnings.

src/main/java/me/moodcat/core/App.java, src/test/java/me/moodcat/core/AppTest.java, src/test/java/me/moodcat/core/mappers/EntityNotFoundExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/IllegalArgumentExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/NotFoundExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/ThrowableMapperTest.java, src/test/java/me/moodcat/database/entities/ArtistTest.java, src/test/java/me/moodcat/database/entities/ChatMessageTest.java, src/test/java/me/moodcat/database/entities/RoomTest.java, src/test/java/me/moodcat/database/entities/SongTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudExceptionTest.java
Add and extend tests across the board.
=> Testability closes #97

pom.xml, src/test/java/me/moodcat/database/embeddables/VAVectorTest.java, src/test/java/me/moodcat/database/entities/ArtistTest.java, src/test/java/me/moodcat/database/entities/ChatMessageTest.java, src/test/java/me/moodcat/database/entities/RoomTest.java, src/test/java/me/moodcat/database/entities/SongTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudExtractTest.java
Some changes that I remembered just after I accepted the earlier PR. Oopsie ;p
JUnit-addons offers easier testing of equals and hashcode =]
=> Some very minor changes that I missed at the testability review.

src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/core/mappers/AbstractExceptionMapper.java, src/main/java/me/moodcat/database/BulkInsertApp.java, src/main/java/me/moodcat/database/BulkInsertData.java, src/main/java/me/moodcat/database/DbModule.java, src/main/java/me/moodcat/database/controllers/AbstractDAO.java, src/main/java/me/moodcat/database/controllers/ArtistDAO.java, src/main/java/me/moodcat/database/controllers/ChatDAO.java, src/main/java/me/moodcat/database/controllers/RoomDAO.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/database/embeddables/VAVector.java, src/main/java/me/moodcat/database/entities/Artist.java, src/main/java/me/moodcat/database/entities/ChatMessage.java, src/main/java/me/moodcat/database/entities/Room.java, src/main/java/me/moodcat/database/entities/Song.java, src/main/java/me/moodcat/mood/Mood.java, src/main/java/me/moodcat/soundcloud/SoundCloudAPIConnector.java, src/main/java/me/moodcat/soundcloud/SoundCloudException.java, src/main/java/me/moodcat/soundcloud/SoundCloudExtract.java, src/main/java/me/moodcat/soundcloud/SoundCloudSearch.java, src/main/java/me/moodcat/soundcloud/SoundCloudTrack.java
Also removed all @author tags.
=> Documentated all getters and setters fixes #104

README.md, pom.xml, src/main/assembly/jar-with-dependencies.xml, src/test/java/me/moodcat/database/bootstrapper/Bootstrapper.java
Run using  java -jar target/moodcat-core-distribution/moodcat-core/moodcat-core.jar
=> Fixed JAR build

README.md, src/main/java/me/moodcat/core/App.java
Some last changes for the ZIP delivery to SIG.
=> Fixing the build

.travis.yml
Let's first check if this commit correctly works.
Else we have to update our pom.xml with various executions.
=> Updated Octopull webhook according to guidelines.

src/main/java/me/moodcat/core/mappers/AbstractExceptionMapper.java, src/test/java/me/moodcat/core/mappers/EntityNotFoundExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/ExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/IllegalArgumentExceptionMapperTest.java, src/test/java/me/moodcat/core/mappers/NotFoundExceptionMapperTest.java, src/test/java/me/moodcat/soundcloud/SoundCloudTrackTest.java
Also added SoundCloudTrackTest.
=> Removed duplication factor in ExceptionMapperTests.

src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/database/controllers/AbstractDAO.java, src/main/java/me/moodcat/database/controllers/SongDAO.java, src/main/java/me/moodcat/database/embeddables/VAVector.java, src/test/java/TestPackageAppRunner.java
Compatible version for user-classification with frontend.
=> User classification

src/dev/java/me/moodcat/database/bulkInsert/BulkInsertData.java, src/main/java/me/moodcat/api/models/SongModel.java, src/main/java/me/moodcat/database/entities/Song.java, src/main/java/me/moodcat/soundcloud/SoundCloudExtract.java, src/main/java/me/moodcat/soundcloud/SoundCloudTrack.java
=> Purchase url rebase

src/test/java/me/moodcat/api/UserAPITest.java
Added some tests for UserAPI. Pretty straightforward.
=> Added tests for UserAPI. Closes #147

src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/api/UserAPI.java, src/main/java/me/moodcat/api/filters/AwardPoints.java, src/main/java/me/moodcat/api/filters/AwardPointsFilter.java, src/main/java/me/moodcat/core/MoodcatServletModule.java, src/main/java/me/moodcat/database/controllers/UserDAO.java, src/main/resources/persistence.properties, src/test/java/me/moodcat/api/RoomAPITest.java, src/test/java/me/moodcat/api/SongAPITest.java, src/test/java/me/moodcat/api/UserAPITest.java, src/test/java/me/moodcat/database/controllers/UserDAOTest.java
This will break with the current frontend master, so we have to create a fix for that too.
=> Refactored user id's to current user.

src/main/java/me/moodcat/api/SongAPI.java, src/main/java/me/moodcat/api/models/ChatMessageModel.java, src/main/java/me/moodcat/core/App.java, src/test/java/endtoend/ApiEndToEndTest.java, src/test/java/endtoend/ChatMessagesEndToEndTest.java, src/test/java/endtoend/EndToEndTest.java, src/test/java/endtoend/ExceptionHandlingEndToEndTest.java, src/test/java/endtoend/PointsEndToEndTest.java, src/test/java/me/moodcat/database/bootstrapper/Bootstrapper.java, src/test/java/me/moodcat/database/provider/ConnectionProvider.java, src/test/resources/bootstrap/fall-out-boy.json, src/test/resources/persistence.properties
Took quite some effort to get them working, as I had to come up with solutions for POST-requests and to mock the SoundCloud oAuth login.
Not the nicest code, but it works ;p
=> Written 3 more EndToEndTests.

src/main/java/me/moodcat/api/RoomAPI.java, src/main/java/me/moodcat/backend/rooms/RoomInstance.java, src/test/java/me/moodcat/api/RoomAPITest.java, src/test/java/me/moodcat/backend/rooms/RoomBackendTest.java, src/test/java/me/moodcat/backend/rooms/RoomInstanceTest.java
Fixes https://github.com/MoodCat/MoodCat.me-Frontend/issues/84
=> Truncating of messages. Fixes #84.

src/dev/java/me/moodcat/database/bulkInsert/BulkInsertData.java, src/dev/java/me/moodcat/database/bulkInsert/NameGenerator.java
Add a name generator for room names.
=> Implement name generator

src/main/java/me/moodcat/api/SongAPI.java
The classification endpoint is abused for the classify game. We should compensate for that, otherwise the vectors are modified way too less.
=> Set VA initial

src/main/java/me/moodcat/backend/rooms/RoomInstance.java, src/main/java/me/moodcat/backend/rooms/RoomInstanceInUnitOfWork.java, src/main/java/me/moodcat/database/embeddables/VAVector.java, src/test/java/me/moodcat/backend/BackendTest.java, src/test/java/me/moodcat/backend/rooms/RoomBackendTest.java
Rebased version of #175 with different solution.
=> Proposal: strengthen VAVectors on vote up

src/main/java/me/moodcat/api/ProfanityChecker.java, src/test/java/me/moodcat/api/ProfanityCheckerTest.java
Fixes https://github.com/MoodCat/MoodCat.me-Frontend/issues/146
=> Fixes #146.
